openapi: 3.0.3
info:
  title: NepalEntityService API
  version: 0.1.3
  description: |
    The EntityService loads the entity database (person, organizations, govt. bodies, etc.) and exposes endpoints for search, lookup, versions, and relationships. This will live in the public domain., internal microservice providing **read-only** (for now) endpoints for search, lookup, versions, and relationships.
servers:
  - url: http://localhost:9019
    description: InternalHostingUrl
tags:
  - name: Schemas
  - name: Entities
  - name: Relationships
  - name: Versions
paths:
  /schemas:
    get:
      tags: [Schemas]
      summary: List available entity type schemas
      responses:
        '200':
          description: Supported schemas
          content:
            application/json:
              schema:
                type: object
                properties:
                  types:
                    type: array
                    items:
                      type: string
                    example: [PERSON, ORGANIZATION, GOV_BODY]
  /schemas/{type}:
    get:
      tags: [Schemas]
      summary: Get JSON Schema for a specific entity type
      parameters:
        - name: type
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/EntityType'
      responses:
        '200':
          description: JSON Schema for the entity type
          content:
            application/schema+json:
              schema:
                type: object
        '404':
          $ref: '#/components/responses/NotFound'
  /entities:
    get:
      tags: [Entities]
      summary: List/search entities
      operationId: listEntities
      parameters:
        - $ref: '#/components/parameters/q'
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: Paged list of entities
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Entity'
                  page:
                    $ref: '#/components/schemas/CursorPage'
  /entities/{id}:
    get:
      tags: [Entities]
      summary: Get an entity by ID
      operationId: getEntity
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: The entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
        '404':
          $ref: '#/components/responses/NotFound'
  /versions/{id}:
    get:
      tags: [Versions]
      summary: List versions for an entity
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: Version list
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/VersionDetails'
                  page:
                    $ref: '#/components/schemas/CursorPage'
  /entities/{id}/versions/{versionNumber}:
    get:
      tags: [Entities]
      summary: Get entity at a specific version
      parameters:
        - $ref: '#/components/parameters/id'
        - name: versionNumber
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Entity at specified version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
        '404':
          $ref: '#/components/responses/NotFound'
  /entities/{id}/relationships:
    get:
      tags: [Relationships]
      summary: List relationships for an entity
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Relationships
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Relationship'
components:
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: string
        description: UUID
    q:
      name: q
      in: query
      description: Search query
      schema:
        type: string
    type:
      name: type
      in: query
      schema:
        $ref: '#/components/schemas/EntityType'
    limit:
      name: limit
      in: query
      description: Page size
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
  responses:
    NotFound:
      description: Resource not found
  schemas:
    # While not strictly needed, these schemas are added to explain the type of entity response
    EntityType:
      type: string
      enum: [PERSON, ORGANIZATION, GOV_BODY]
    Entity:
      type: object
      required: [id, type, names, versionInfo, createdAt]
      properties:
        id:
          type: string
          description: UUID
          example: "entity:550e8400-sagar-dhakal"
        type:
          $ref: '#/components/schemas/EntityType'
        names:
          type: array
          items:
            $ref: '#/components/schemas/Name'
          description: Localized names
        identifiers:
          type: object
          additionalProperties: true
          description: External identifiers (tax_id, registration_number, etc.)
        tags:
          type: array
          items:
            type: string
        attributes:
          type: object
          additionalProperties: true
          description: Flexible attributes for any entity type
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/ContactInfo'
          description: Contact information list
        versionInfo:
          $ref: '#/components/schemas/Version'
        createdAt:
          type: string
          format: date-time
          description: Initial creation timestamp of the entity
      example:
        id: "550e8400-sagar-dhakal"
        type: "PERSON"
        names:
          - value: "Sagar Dhakal"
            lang: "en"
          - value: "सागर ढकाल"
            lang: "ne"
        tags: ["politician", "activist", "engineer", "youth"]
        attributes:
          birthDate: "1990-01-05"
          occupation: "Hydro-mechanical engineer"
          education: "Bachelors"
        contacts:
          - type: "FACEBOOK"
            value: "https://www.facebook.com/sagardhakaler"
        versionInfo:
          id: "version:entity:550e8400-sagar-dhakal:1"
          versionNumber: 1
          actor:
            id: "user123"
            name: "Admin User"
          changeDescription: "Initial entity creation"
          date: "2024-01-15T10:30:00Z"
        createdAt: "2024-01-15T10:30:00Z"

    Relationship:
      type: object
      required: [id, sourceId, targetId, type, versionInfo]
      properties:
        id:
          type: string
        sourceId:
          type: string
        targetId:
          type: string
        type:
          type: string
          enum: [AFFILIATED_WITH, EMPLOYED_BY, MEMBER_OF, PARENT_OF, CHILD_OF, SUPERVISES, LOCATED_IN]
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        attributes:
          type: object
          additionalProperties: true
        versionInfo:
          $ref: '#/components/schemas/Version'
        createdAt:
          type: string
          format: date-time
    Version:
      type: object
      required: [id, versionNumber, actor, changeDescription, date]
      properties:
        id:
          type: string
          description: Version ID in format version:<entity/relationship>:<ID>:number
        versionNumber:
          type: integer
          description: Version number
        actor:
          type: object
          required: [id]
          properties:
            id:
              type: string
              description: User/system ID who made the change
            name:
              type: string
              description: Display name of actor
        changeDescription:
          type: string
          description: Description of changes made in this version
        date:
          type: string
          format: date-time
          description: When this version was created
    VersionDetails:
      allOf:
        - $ref: '#/components/schemas/Version'
        - type: object
          required: [type, createdAt]
          properties:
            type:
              type: string
              enum: [ENTITY, RELATIONSHIP]
              description: Type of object this version tracks
            changes:
              type: object
              additionalProperties: true
              description: JSON patch of what changed
    CursorPage:
      type: object
      properties:
        after:
          type: string
          nullable: true
        hasMore:
          type: boolean
    ContactInfo:
      type: object
      required: [type, value]
      properties:
        type:
          type: string
          enum: [EMAIL, PHONE, ADDRESS, WEBSITE, FACEBOOK, TWITTER, WHATSAPP, INSTAGRAM, TIKTOK, YOUTUBE]
          description: Type of contact information
        value:
          type: string
          description: Contact value
        label:
          type: string
          description: Optional label for the contact
    Name:
      type: object
      required: [value, lang]
      properties:
        value:
          type: string
          description: Name value
        lang:
          type: string
          description: BCP-47 language code
          example: en
