"""Tests for OpenAIProvider.

These tests verify the OpenAI provider implementation for LLM-powered
data extraction and normalization tasks.
"""

import json
import os
import sys
from unittest.mock import AsyncMock, MagicMock, patch

import pytest


# Fixture to mock environment variables for all tests in this module
@pytest.fixture(autouse=True)
def mock_env(monkeypatch):
    """Mock environment variables for OpenAIProvider so tests don’t depend on .env."""
    monkeypatch.setenv("OPENAI_API_KEY", "sk-testkey123")
    monkeypatch.setenv("OPENAI_API_BASE", "https://api.openai.com/v1")
    monkeypatch.setenv("OPENAI_MODEL", "gpt-5-mini")


# Mock openai before importing the provider
mock_async_openai_instance = AsyncMock()
mock_async_openai_class = MagicMock(return_value=mock_async_openai_instance)
sys.modules["openai"] = MagicMock(AsyncOpenAI=mock_async_openai_class)


class TestOpenAIProviderInitialization:
    """Test OpenAI provider initialization."""

    def test_provider_initialization_default(self):
        """Test provider initialization with default settings."""
        from nes.services.scraping.providers import OpenAIProvider

        provider = OpenAIProvider()
        assert provider is not None
        assert provider.model_id == "gpt-5-mini"

    def test_provider_initialization_custom_model(self, monkeypatch):
        """Test provider initialization with custom model."""
        monkeypatch.delenv("OPENAI_MODEL", raising=False)
        from nes.services.scraping.providers import OpenAIProvider

        provider = OpenAIProvider(model_id="gpt-4o-2025-01-01")
        assert provider.model_id == "gpt-4o-2025-01-01"

    def test_provider_initialization_with_api_key(self):
        """Test initialization with explicit API key."""
        from nes.services.scraping.providers import OpenAIProvider

        provider = OpenAIProvider(api_key="sk-testkey123")
        # Nothing special to assert besides no error; maybe api_key set internally
        assert provider is not None


class TestOpenAIProviderTextGeneration:
    """Test text generation capabilities."""

    @pytest.mark.asyncio
    async def test_generate_text_basic(self):
        """Test basic text generation."""
        import openai

        mock_resp = AsyncMock()
        mock_choice = MagicMock()
        mock_choice.message.content = "Generated by OpenAI"
        mock_resp.choices = [mock_choice]
        mock_async_openai_instance.chat.completions.create.return_value = mock_resp

        from nes.services.scraping.providers import OpenAIProvider

        provider = OpenAIProvider()
        result = await provider.generate_text(prompt="Hello world")
        assert result == "Generated by OpenAI"

    @pytest.mark.asyncio
    async def test_generate_text_with_system_prompt(self):
        """Test generation when system prompt provided."""
        import openai

        mock_resp = AsyncMock()
        mock_choice = MagicMock()
        mock_choice.message.content = "Response with system prompt"
        mock_resp.choices = [mock_choice]
        mock_async_openai_instance.chat.completions.create.return_value = mock_resp

        from nes.services.scraping.providers import OpenAIProvider

        provider = OpenAIProvider()
        result = await provider.generate_text(
            prompt="User asks something", system_prompt="System: you are helpful"
        )
        assert result == "Response with system prompt"


class TestOpenAIProviderStructuredExtraction:
    """Test structured data extraction."""

    @pytest.mark.asyncio
    async def test_extract_structured_data_simple(self):
        """Test extracting structured data given schema."""
        import openai

        mock_resp = AsyncMock()
        mock_choice = MagicMock()
        # Return JSON string as content
        mock_choice.message.content = json.dumps({"field1": "value1", "field2": 42})
        mock_resp.choices = [mock_choice]
        mock_async_openai_instance.chat.completions.create.return_value = mock_resp

        from nes.services.scraping.providers import OpenAIProvider

        provider = OpenAIProvider()
        schema = {
            "type": "object",
            "properties": {
                "field1": {"type": "string"},
                "field2": {"type": "integer"},
            },
            "required": ["field1", "field2"],
        }
        result = await provider.extract_structured_data(
            text="Some input text",
            schema=schema,
            instructions="Extract field1 and field2",
        )
        assert result["field1"] == "value1"
        assert result["field2"] == 42

    @pytest.mark.asyncio
    async def test_extract_structured_data_bad_json(self):
        """Test extraction when JSON parse fails (returns empty dict)."""
        import openai

        mock_resp = AsyncMock()
        mock_choice = MagicMock()
        mock_choice.message.content = "Not a JSON"
        mock_resp.choices = [mock_choice]
        mock_async_openai_instance.chat.completions.create.return_value = mock_resp

        from nes.services.scraping.providers import OpenAIProvider

        provider = OpenAIProvider()
        schema = {}
        result = await provider.extract_structured_data(
            text="Irrelevant text", schema=schema, instructions="Whatever"
        )
        assert result == {}


class TestOpenAIProviderTranslate:
    """Test translation functionality."""

    @pytest.mark.asyncio
    async def test_translate_nepali_to_english(self):
        """Test translating Nepali to English."""
        import openai

        mock_resp = AsyncMock()
        mock_choice = MagicMock()
        mock_choice.message.content = "Ram Chandra Poudel"
        mock_resp.choices = [mock_choice]
        mock_async_openai_instance.chat.completions.create.return_value = mock_resp

        from nes.services.scraping.providers import OpenAIProvider

        provider = OpenAIProvider()
        result = await provider.translate(
            text="राम चन्द्र पौडेल", source_lang="ne", target_lang="en"
        )
        assert result == "Ram Chandra Poudel"

    @pytest.mark.asyncio
    async def test_translate_english_to_nepali(self):
        """Test translating English to Nepali."""
        import openai

        mock_resp = AsyncMock()
        mock_choice = MagicMock()
        mock_choice.message.content = "राम चन्द्र पौडेल"
        mock_resp.choices = [mock_choice]
        mock_async_openai_instance.chat.completions.create.return_value = mock_resp

        from nes.services.scraping.providers import OpenAIProvider

        provider = OpenAIProvider()
        result = await provider.translate(
            text="Ram Chandra Poudel", source_lang="en", target_lang="ne"
        )
        assert result == "राम चन्द्र पौडेल"
